### ISSUE TITLE
Cannot publish box with empty description

### ISSUE THREAD

**Issue by osomme** [osomme/BookzBox-client#49]
Bug reported by Thomas

**Comment by osomme** [comment]
Probably related to geolocation service not returning a value from an async function

**Comment by HTSkole** [comment]
Location service now has a 3 second timeout. An error is displayed if the app fails to fetch the users location. It is still unknown if this fixes this bug as it is difficult to reproduce. 

This bug also asks the question: "What does description have to do with anything?". It seems likely that it is just an unfortunate coincidence and that it doesn't actually have anything to do with this bug. I am therefore closing this issue.
